/*ALL'INTERNO DEL FILE SONO DEFINITE LE DICHIARAZIONI DEI BYTE CHE IL CLIENT E IL SERVER SI INVIANO PER COMUNICARE COMANDI E LE LORO ESECUZIONI (ERRORI O NO)*/
#define LEN_MSG_SERVER 2
char REGISTRAZIONE[LEN_MSG_SERVER] = "A";
char ACCEDI[LEN_MSG_SERVER] = "B";
char LOOK[LEN_MSG_SERVER] = "C";
char LOOK_PARAMETRO[LEN_MSG_SERVER] = "D";
char TAKE[LEN_MSG_SERVER] = "E";
char USE1[LEN_MSG_SERVER] = "F";
char USE2[LEN_MSG_SERVER] = "G";
char OBJ[LEN_MSG_SERVER] = "H";
char DROP[LEN_MSG_SERVER] = "I";
char END[LEN_MSG_SERVER] = "L";
char AIUTANTE[LEN_MSG_SERVER] = "M";
char GIOCATORE[LEN_MSG_SERVER] = "N";
char OPERAZIONE_RIUSCITA[LEN_MSG_SERVER] = "O";
char OPERAZIONE_FALLITA[LEN_MSG_SERVER] = "P";
char OGGETTI_LIMITE[LEN_MSG_SERVER] = "Q";
char OGGETTO_NON_TROVATO[LEN_MSG_SERVER] = "R";
char OGGETTO_GIA_RACCOLTO[LEN_MSG_SERVER] = "S";
char OGGETTO_STATO_ALTO[LEN_MSG_SERVER] = "T"; //l'oggetto puo' essere raccolto solo quando il giocatoe risolve enigmi altrove
char OGGETTO_ENIGMA[LEN_MSG_SERVER] = "U";
char ESCAPE_ROOM_VINTA[LEN_MSG_SERVER] = "V";
char ENIGMA_RISOLTO[LEN_MSG_SERVER] = "W";
char OGGETTO_NON_INVENTARIO[LEN_MSG_SERVER] = "X";
char OGGETTI_NON_INSIEME[LEN_MSG_SERVER] = "Y";